name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      newversion:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'New version (patch/minor/major)'
        # Default value if no value is explicitly provided
        default: 'patch'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: pwd
      run: pwd
    - name: cd ..
      run: cd
    - name: ls
      run: ls
    - name: Release
      run: npm run test-github-actions ${{ github.event.inputs.name }}
